// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import BookmarkConcept from "./Bookmark/BookmarkConcept.ts";
import PlaceCatalogConcept from "./PlaceCatalog/PlaceCatalogConcept.ts";
import LikertSurveyConcept from "./LikertSurvey/LikertSurveyConcept.ts";
import InterestFilterConcept from "./InterestFilter/InterestFilterConcept.ts";
import UserAuthConcept from "./UserAuth/UserAuthConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import MediaLibraryConcept from "./MediaLibrary/MediaLibraryConcept.ts";

export type { default as BookmarkConcept } from "./Bookmark/BookmarkConcept.ts";
export type { default as PlaceCatalogConcept } from "./PlaceCatalog/PlaceCatalogConcept.ts";
export type { default as LikertSurveyConcept } from "./LikertSurvey/LikertSurveyConcept.ts";
export type { default as InterestFilterConcept } from "./InterestFilter/InterestFilterConcept.ts";
export type { default as UserAuthConcept } from "./UserAuth/UserAuthConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as MediaLibraryConcept } from "./MediaLibrary/MediaLibraryConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const Bookmark = Engine.instrumentConcept(new BookmarkConcept(db));
export const PlaceCatalog = Engine.instrumentConcept(
  new PlaceCatalogConcept(db),
);
export const LikertSurvey = Engine.instrumentConcept(
  new LikertSurveyConcept(db),
);
export const InterestFilter = Engine.instrumentConcept(
  new InterestFilterConcept(db),
);
export const UserAuth = Engine.instrumentConcept(new UserAuthConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const MediaLibrary = Engine.instrumentConcept(
  new MediaLibraryConcept(db),
);
